name: finbuddy_ai
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_ai: ^3.5.0
  firebase_app_check: ^0.4.1+2
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  cloud_firestore: ^6.1.0
  go_router: ^17.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3
  flutter_form_builder: ^10.2.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  google_sign_in: ^7.2.0
  firebase_auth: ^6.1.2
  intl: ^0.20.2
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  riverpod_generator: ^3.0.3

flutter:
  uses-material-design: true

flutter_native_splash:
  # Path to your splash screen image
  image: assets/logo.png

  # Background color (HEX code without the #)
  color: "0f172a"

  # Branding image (using the same image for simplicity)
  branding: assets/logo.png

  # Android 12+ configuration
  android_12:
    image: assets/logo.png
    color: "0f172a"

  # Enable for iOS generation
  ios: true

  # General settings
  fullscreen: true
  web: false
